index:
  path: /home
  controller: App\Controller\HomeController::index

app_login:
  path: /
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_usuarios:
  path: /usuarios
  controller: App\Controller\UsuariosController::usuarios

api_buscar_producto:
  path: /findBySimilarName
  controller: App\Controller\ApiController::findBySimilarName
  methods: ["POST"]
