index:
  path: /home
  controller: App\Controller\HomeController::index

app_login:
  path: /
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_usuarios:
  path: /usuarios
  controller: App\Controller\UsuariosController::usuarios

app_productos:
  path: /productos
  controller: App\Controller\ProductosController::productos

app_pedidos:
  path: /pedidos
  controller: App\Controller\PedidoController::pedidos

api_get_usuario:
  path: /api/usuarios/{id}
  controller: App\Controller\ApiController::getUsuario
  methods: ["GET"]

api_get_usuarios:
  path: /api/usuarios
  controller: App\Controller\ApiController::getUsuarios
  methods: ["GET"]

api_get_producto:
  path: /api/productos/{id}
  controller: App\Controller\ApiController::getProducto
  methods: ["GET"]

api_get_productos:
  path: /api/productos
  controller: App\Controller\ApiController::getProductos
  methods: ["GET"]

api_get_tipoproducto:
  path: /api/tipoproducto/{nombre}
  controller: App\Controller\ApiController::getTipoProducto
  methods: ["GET"]

api_get_tienda:
  path: /api/tiendas/{id}
  controller: App\Controller\ApiController::getTienda
  methods: ["GET"]

api_get_tiendas:
  path: /api/tiendas
  controller: App\Controller\ApiController::getTiendas
  methods: ["GET"]

api_get_pedidos:
  path: /api/pedidos
  controller: App\Controller\ApiController::getPedidos
  methods: ["GET"]

api_post_producto:
  path: /api/productos
  controller: App\Controller\ApiController::postProducto
  methods: ["POST"]

api_post_tienda:
  path: /api/tiendas
  controller: App\Controller\ApiController::postTienda
  methods: ["POST"]

api_put_producto:
  path: /api/productos/{id}
  controller: App\Controller\ApiController::putProducto
  methods: ["PUT"]

api_put_tienda:
  path: /api/tiendas/{id}
  controller: App\Controller\ApiController::putTienda
  methods: ["PUT"]

api_delete_tienda:
  path: /api/tiendas/{id}
  controller: App\Controller\ApiController::deleteTienda
  methods: ["DELETE"]

api_delete_producto:
  path: /api/productos/{id}
  controller: App\Controller\ApiController::deleteProducto
  methods: ["DELETE"]

api_buscar_producto:
  path: /findBySimilarName
  controller: App\Controller\ApiAjaxController::findBySimilarName
  methods: ["POST"]

